### ISSUE TITLE
Unable to install qds-sdk-py. Error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [qubole/qds-sdk-py#123]
* [Here](https://gist.github.com/amelio-vazquez-reina/ac3ad771604f94c74f15) is the list of packages in my environment. Note that it includes the [latest](https://pypi.python.org/pypi/wheel) `wheel` (0.26.0)
* Inspecting my environment: 
```
In [1]: import wheel

In [2]: wheel.__file__
Out[2]: '/Users/avazquez/anaconda3/envs/py35/lib/python3.5/site-packages/wheel/__init__.py'

In [3]: wheel.__version__
Out[3]: '0.26.0'
```
* All using a Python 3.5 in OSX from a conda install:
```
$ python --version
Python 3.5.0 :: Continuum Analytics, Inc.
```

* And finally the full trace of `$ pip install qds-sdk`
 ```
Building wheels for collected packages: qds-sdk
  Running setup.py bdist_wheel for qds-sdk
  Complete output from command /Users/avazquez/anaconda3/envs/py35/bin/python3 -c "import setuptools;__file__='/private/var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/pip-build-k8fufyo7/qds-sdk/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/yl/bqcgdj3d6ss_mrfkpzxlh89m0000gp/T/tmpmprq00c1pip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for qds-sdk
Failed to build qds-sdk
Installing collected packages: qds-sdk
       Running setup.py install for qds-sdk
Successfully installed qds-sdk-1.7.0
```

**Comment by mindprince** [comment]
Surprising. I tried installing it in a virtualenv using Python 3.5 and it worked perfectly.

Also, in the list of packages in your environment, I already see qds-sdk 1.7.0.

Not sure what the problem is. :-(

**Comment by amelio-vazquez-reina** [comment]
Thanks @mindprince The list of packages includes `qds-sdk-py` because apparently, even though that step fails, pip continues to install `qds-sdk` (I expanded the trace in the OP to highlight that).

**Comment by amelio-vazquez-reina** [comment]
@mindprince What version of `wheel` did you install `qds-sdk-py` against in that virtualenv?

**Comment by mindprince** [comment]
I used the same version as you: `0.26.0`.

So, pip continues installing qds-sdk and says it was successfully installed. Does it work after that?

**Comment by mindprince** [comment]
Hi @amelio-vazquez-reina 

Any updates on this?
