### ISSUE TITLE
Tags in the CLI

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [qubole/qds-sdk-py#160]
Is there any way to declare tags in the CLI?

**Comment by harshshah87** [comment]
Is it for the instance tags? During cluster create/update:

--custom-ec2-tags: Custom ec2 tags to be set on all instances of the cluster. Specified as JSON object (key-value pairs) e.g. --custom-ec2-tags '{"key1":"value1", "key2":"value2"}'.

**Comment by amelio-vazquez-reina** [comment]
Thanks. Yes, when running queries. I guess I was hoping to see the full list of arguments one can use with a `hivecmd`. It looks like `--tags` is one of them.

**Comment by harshshah87** [comment]
"qds.py --token "XXX" hivecmd run --help"  should display all options.  Will close this issue for now. Re-open in case I can answer any more questions.
