### ISSUE TITLE
Error: Status code 449 (RetryWithDelay)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [qubole/qds-sdk-py#165]
I just started running into this error for some of my queries

```
qds.py --token=$QUBOLE_KEY_AVAZQUEZ hivecmd getresult 28597419 > my_data.csv
Error: Status code 449 (RetryWithDelay) from url https://api.qubole.com/api/v1.2/commands/28597419/results?inline=True
```

I am having this problem in Python 2.7.x and Python 3.5.x.

**Comment by chattarajoy** [comment]
@amelio-vazquez-reina status 449 means the results of the command are not available yet on Qubole, please contact Qubole Support if the problem persists.
