### ISSUE TITLE
get_results into a file

### ISSUE THREAD

**Issue by samratisking** [qubole/qds-sdk-py#198]
Hi,

The comments provided in the code are not helpful in understanding how to retrieve the results into 'fp'. It is mentioned that the get_results() can be redirected to 'fp'. But an example of how to provide the details for this file stream 'fp' would be really appreciated.

Best Regards,
Sam

**Comment by mcarlsen** [comment]
You should be able to use any file-like object that you can write bytes to. E.g. `my_hive_command.get_results(fp=open('/tmp/outfile', 'wb'))`

**Comment by wmoussa** [comment]
@mcarlsen did Qubole stopped supporting this project? seems several PR could be merged.

**Comment by chattarajoy** [comment]
Closing as this is working, we are working on better docs btw.
