### ISSUE TITLE
Updating cluster to modify cluster composition does not work

### ISSUE THREAD

**Issue by shivanga** [qubole/qds-sdk-py#326]
For pushing configs, I use `class ClusterInfoV22` to modify cluster composition, to update the cluster when I am using the `ClusterV2.update()` , it uses api_version as `v2` as in code below
```
class ClusterV2(Resource):
    rest_entity_path = "clusters"
    api_version = "v2"
```
which causes the pushing of composition to not work, as api `v2.2` is required for it.

**Comment by chattarajoy** [comment]
@akaranjkar-qu @harshshah87 can you please take a look? Or tag someone who can look into this?

**Comment by tarrygo** [comment]
@shivanga You can set api_version as 
`ClusterV2.api_version` = "v2.2"`
and then call `ClusterV2.update()`
